export const DEFAULT_USER_SETTINGS = {
  emailNotifications: true,
  smsAlerts: true,
  systemNotifications: true,
  weeklyReports: false,
  appointmentReminders: true,
  labResultEmails: true,
  criticalAlerts: true,
  adminDigest: true,
  doctorScheduleAlerts: true,
  patientRecordSharing: false,
  theme: 'system',
  density: 'comfortable',
  language: 'en',
  timezone: 'Asia/Calcutta',
  defaultDashboard: 'overview',
  twoFactorEnabled: false,
  dataSharing: false,
  profileVisibility: 'care_team',
};

export const mergeSettings = (...settingsList) => settingsList.reduce(
  (merged, settings) => ({ ...merged, ...(settings || {}) }),
  { ...DEFAULT_USER_SETTINGS },
);

export function readStoredSettings() {
  if (typeof localStorage === 'undefined') return {};
  try {
    return JSON.parse(localStorage.getItem('medicore_settings') || '{}');
  } catch {
    return {};
  }
}

export function applyUserSettings(settings = {}) {
  if (typeof document === 'undefined') return mergeSettings(settings);

  const next = mergeSettings(readStoredSettings(), settings);
  const root = document.documentElement;
  const prefersDark = typeof window !== 'undefined' && window.matchMedia('(prefers-color-scheme: dark)').matches;

  root.classList.toggle('dark', next.theme === 'dark' || (next.theme === 'system' && prefersDark));
  root.dataset.density = next.density;
  root.dataset.language = next.language;
  root.lang = next.language || 'en';
  root.dir = 'ltr';

  if (typeof localStorage !== 'undefined') {
    localStorage.setItem('medicore_settings', JSON.stringify(next));
  }

  return next;
}

const en = {
  'nav.dashboard': 'Dashboard',
  'nav.manageUsers': 'Manage Users',
  'nav.manageDoctors': 'Manage Doctors',
  'nav.managePatients': 'Manage Patients',
  'nav.appointments': 'Appointments',
  'nav.medicalRecords': 'Medical Records',
  'nav.billing': 'Billing',
  'nav.departments': 'Departments',
  'nav.reviews': 'Reviews',
  'nav.analytics': 'Analytics',
  'nav.emergency': 'Emergency',
  'nav.importExport': 'Import/Export',
  'nav.reports': 'Reports',
  'nav.notifications': 'Notifications',
  'nav.settings': 'Settings',
  'nav.findDoctors': 'Find Doctors',
  'nav.myAppointments': 'My Appointments',
  'nav.labServices': 'Lab Services',
  'nav.uploadFiles': 'Upload Files',
  'nav.myReports': 'My Reports',
  'nav.myBilling': 'My Billing',
  'nav.payments': 'Payments',
  'nav.myReviews': 'My Reviews',
  'nav.myPatients': 'My Patients',
  'nav.consultations': 'Consultations',
  'nav.mySchedule': 'My Schedule',
  'nav.myEarnings': 'My Earnings',
  'common.logout': 'Logout',
  'common.saving': 'Saving...',
  'common.updating': 'Updating...',
  'role.admin': 'admin',
  'role.doctor': 'doctor',
  'role.patient': 'patient',
  'settings.title': 'Settings',
  'settings.subtitle': 'Manage account, security, notifications, and dashboard preferences',
  'settings.profile': 'Profile',
  'settings.roleDetails': 'Role Details',
  'settings.security': 'Security',
  'settings.notifications': 'Notifications',
  'settings.appearance': 'Appearance',
  'settings.privacy': 'Privacy',
  'settings.saved': 'Settings saved successfully.',
  'settings.saveError': 'Unable to save settings.',
  'settings.passwordSaved': 'Password updated successfully.',
  'settings.passwordError': 'Unable to update password.',
  'settings.passwordLength': 'New password must be at least 6 characters.',
  'settings.passwordMismatch': 'New password and confirmation do not match.',
  'settings.profilePhoto': 'Profile Photo',
  'settings.personalInfo': 'Personal Information',
  'settings.fullName': 'Full Name',
  'settings.yourName': 'Your name',
  'settings.emailAddress': 'Email Address',
  'settings.emailLocked': 'Email cannot be changed after registration.',
  'settings.phoneNumber': 'Phone Number',
  'settings.gender': 'Gender',
  'settings.preferNot': 'Prefer not to say',
  'settings.male': 'Male',
  'settings.female': 'Female',
  'settings.other': 'Other',
  'settings.dateOfBirth': 'Date of Birth',
  'settings.avatarUrl': 'Avatar URL',
  'settings.address': 'Address',
  'settings.addressPlaceholder': 'Residential address',
  'settings.saveProfile': 'Save Profile',
  'settings.rolePreferences': 'Role Preferences',
  'settings.specialization': 'Specialization',
  'settings.experience': 'Experience',
  'settings.qualification': 'Qualification',
  'settings.licenseNumber': 'License Number',
  'settings.consultationFee': 'Consultation Fee (Rs)',
  'settings.scheduleAlerts': 'Schedule alerts',
  'settings.scheduleAlertsDesc': 'Notify me when appointments change or urgent cases are assigned.',
  'settings.adminDigest': 'Admin daily digest',
  'settings.adminDigestDesc': 'Receive a summary of registrations, billing, and emergency activity.',
  'settings.criticalAlerts': 'Critical alerts',
  'settings.criticalAlertsDesc': 'Highlight emergency and blocked-account events immediately.',
  'settings.defaultAdminDashboard': 'Default admin dashboard',
  'settings.defaultDoctorDashboard': 'Default doctor dashboard',
  'settings.defaultPatientDashboard': 'Patient dashboard start page',
  'settings.careTeamSharing': 'Care team record sharing',
  'settings.careTeamSharingDesc': 'Allow assigned doctors to see emergency, lab, and visit records.',
  'settings.labResultEmails': 'Lab result emails',
  'settings.labResultEmailsDesc': 'Send lab report availability and attachments to my email.',
  'settings.saveRole': 'Save Role Settings',
  'settings.currentPassword': 'Current Password',
  'settings.newPassword': 'New Password',
  'settings.confirmPassword': 'Confirm New Password',
  'settings.twoFactor': 'Two-factor verification',
  'settings.twoFactorDesc': 'Require OTP verification for sensitive account changes.',
  'settings.updatePassword': 'Update Password',
  'settings.saveSecurity': 'Save Security Settings',
  'settings.notificationPrefs': 'Notification Preferences',
  'settings.emailNotifications': 'Email notifications',
  'settings.emailNotificationsDesc': 'Receive account, appointment, report, and billing emails.',
  'settings.smsAlerts': 'SMS alerts',
  'settings.smsAlertsDesc': 'Get urgent appointment and emergency updates by phone.',
  'settings.systemNotifications': 'System notifications',
  'settings.systemNotificationsDesc': 'Show in-app notifications across your dashboard.',
  'settings.appointmentReminders': 'Appointment reminders',
  'settings.appointmentRemindersDesc': 'Send reminders before upcoming consultations.',
  'settings.weeklyReports': 'Weekly reports',
  'settings.weeklyReportsDesc': 'Receive a weekly summary of activity and important records.',
  'settings.saveNotifications': 'Save Notifications',
  'settings.dashboardAppearance': 'Dashboard Appearance',
  'settings.theme': 'Theme',
  'settings.system': 'System',
  'settings.light': 'Light',
  'settings.dark': 'Dark',
  'settings.density': 'Density',
  'settings.comfortable': 'Comfortable',
  'settings.compact': 'Compact',
  'settings.spacious': 'Spacious',
  'settings.language': 'Language',
  'settings.english': 'English',
  'settings.hindi': 'Hindi',
  'settings.marathi': 'Marathi',
  'settings.timezone': 'Timezone',
  'settings.indiaTime': 'India Standard Time',
  'settings.easternTime': 'Eastern Time',
  'settings.london': 'London',
  'settings.saveAppearance': 'Save Appearance',
  'settings.privacyData': 'Privacy and Data',
  'settings.usageAnalytics': 'Usage analytics',
  'settings.usageAnalyticsDesc': 'Share non-medical usage data to improve dashboard reliability.',
  'settings.profileVisibility': 'Profile visibility',
  'settings.private': 'Private',
  'settings.careTeamOnly': 'Care team only',
  'settings.hospitalStaff': 'Hospital staff',
  'settings.downloadData': 'Download My Data',
  'settings.savePrivacy': 'Save Privacy',
  'option.overview': 'Overview',
  'option.reports': 'Reports',
  'option.billing': 'Billing',
  'option.emergency': 'Emergency',
  'option.appointments': 'Appointments',
  'option.records': 'Medical Records',
  'option.patients': 'Patients',
  'option.earnings': 'Earnings',
  'option.schedule': 'Schedule',
};

const hi = {
  'nav.dashboard': 'डैशबोर्ड',
  'nav.manageUsers': 'यूजर प्रबंधन',
  'nav.manageDoctors': 'डॉक्टर प्रबंधन',
  'nav.managePatients': 'मरीज प्रबंधन',
  'nav.appointments': 'अपॉइंटमेंट',
  'nav.medicalRecords': 'मेडिकल रिकॉर्ड',
  'nav.billing': 'बिलिंग',
  'nav.departments': 'विभाग',
  'nav.reviews': 'रिव्यू',
  'nav.analytics': 'एनालिटिक्स',
  'nav.emergency': 'इमरजेंसी',
  'nav.importExport': 'इंपोर्ट/एक्सपोर्ट',
  'nav.reports': 'रिपोर्ट',
  'nav.notifications': 'नोटिफिकेशन',
  'nav.settings': 'सेटिंग्स',
  'nav.findDoctors': 'डॉक्टर खोजें',
  'nav.myAppointments': 'मेरे अपॉइंटमेंट',
  'nav.labServices': 'लैब सेवाएं',
  'nav.uploadFiles': 'फाइल अपलोड',
  'nav.myReports': 'मेरी रिपोर्ट',
  'nav.myBilling': 'मेरी बिलिंग',
  'nav.payments': 'पेमेंट',
  'nav.myReviews': 'मेरे रिव्यू',
  'nav.myPatients': 'मेरे मरीज',
  'nav.consultations': 'कंसल्टेशन',
  'nav.mySchedule': 'मेरा शेड्यूल',
  'nav.myEarnings': 'मेरी कमाई',
  'common.logout': 'लॉगआउट',
  'common.saving': 'सेव हो रहा है...',
  'common.updating': 'अपडेट हो रहा है...',
  'role.admin': 'एडमिन',
  'role.doctor': 'डॉक्टर',
  'role.patient': 'मरीज',
  'settings.title': 'सेटिंग्स',
  'settings.subtitle': 'अकाउंट, सुरक्षा, नोटिफिकेशन और डैशबोर्ड पसंद प्रबंधित करें',
  'settings.profile': 'प्रोफाइल',
  'settings.roleDetails': 'भूमिका विवरण',
  'settings.security': 'सुरक्षा',
  'settings.notifications': 'नोटिफिकेशन',
  'settings.appearance': 'दिखावट',
  'settings.privacy': 'प्राइवेसी',
  'settings.saved': 'सेटिंग्स सफलतापूर्वक सेव हो गईं।',
  'settings.saveError': 'सेटिंग्स सेव नहीं हो सकीं।',
  'settings.passwordSaved': 'पासवर्ड सफलतापूर्वक अपडेट हो गया।',
  'settings.passwordError': 'पासवर्ड अपडेट नहीं हो सका।',
  'settings.passwordLength': 'नया पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।',
  'settings.passwordMismatch': 'नया पासवर्ड और पुष्टि मेल नहीं खाते।',
  'settings.profilePhoto': 'प्रोफाइल फोटो',
  'settings.personalInfo': 'व्यक्तिगत जानकारी',
  'settings.fullName': 'पूरा नाम',
  'settings.yourName': 'आपका नाम',
  'settings.emailAddress': 'ईमेल पता',
  'settings.emailLocked': 'रजिस्ट्रेशन के बाद ईमेल बदला नहीं जा सकता।',
  'settings.phoneNumber': 'फोन नंबर',
  'settings.gender': 'लिंग',
  'settings.preferNot': 'नहीं बताना चाहते',
  'settings.male': 'पुरुष',
  'settings.female': 'महिला',
  'settings.other': 'अन्य',
  'settings.dateOfBirth': 'जन्म तारीख',
  'settings.avatarUrl': 'अवतार URL',
  'settings.address': 'पता',
  'settings.addressPlaceholder': 'रहने का पता',
  'settings.saveProfile': 'प्रोफाइल सेव करें',
  'settings.rolePreferences': 'भूमिका सेटिंग्स',
  'settings.specialization': 'स्पेशलाइजेशन',
  'settings.experience': 'अनुभव',
  'settings.qualification': 'योग्यता',
  'settings.licenseNumber': 'लाइसेंस नंबर',
  'settings.consultationFee': 'कंसल्टेशन फीस (Rs)',
  'settings.scheduleAlerts': 'शेड्यूल अलर्ट',
  'settings.scheduleAlertsDesc': 'अपॉइंटमेंट बदलने या जरूरी केस मिलने पर सूचना दें।',
  'settings.adminDigest': 'एडमिन दैनिक सारांश',
  'settings.adminDigestDesc': 'रजिस्ट्रेशन, बिलिंग और इमरजेंसी गतिविधि का सारांश पाएं।',
  'settings.criticalAlerts': 'महत्वपूर्ण अलर्ट',
  'settings.criticalAlertsDesc': 'इमरजेंसी और अकाउंट ब्लॉक घटनाओं को तुरंत दिखाएं।',
  'settings.defaultAdminDashboard': 'डिफॉल्ट एडमिन डैशबोर्ड',
  'settings.defaultDoctorDashboard': 'डिफॉल्ट डॉक्टर डैशबोर्ड',
  'settings.defaultPatientDashboard': 'डिफॉल्ट मरीज डैशबोर्ड',
  'settings.careTeamSharing': 'केयर टीम रिकॉर्ड शेयरिंग',
  'settings.careTeamSharingDesc': 'असाइन किए गए डॉक्टरों को इमरजेंसी, लैब और विजिट रिकॉर्ड देखने दें।',
  'settings.labResultEmails': 'लैब रिजल्ट ईमेल',
  'settings.labResultEmailsDesc': 'लैब रिपोर्ट उपलब्धता और अटैचमेंट ईमेल पर भेजें।',
  'settings.saveRole': 'भूमिका सेटिंग्स सेव करें',
  'settings.currentPassword': 'वर्तमान पासवर्ड',
  'settings.newPassword': 'नया पासवर्ड',
  'settings.confirmPassword': 'नया पासवर्ड पुष्टि करें',
  'settings.twoFactor': 'टू-फैक्टर वेरिफिकेशन',
  'settings.twoFactorDesc': 'संवेदनशील बदलावों के लिए OTP वेरिफिकेशन मांगें।',
  'settings.updatePassword': 'पासवर्ड अपडेट करें',
  'settings.saveSecurity': 'सुरक्षा सेटिंग्स सेव करें',
  'settings.notificationPrefs': 'नोटिफिकेशन पसंद',
  'settings.emailNotifications': 'ईमेल नोटिफिकेशन',
  'settings.emailNotificationsDesc': 'अकाउंट, अपॉइंटमेंट, रिपोर्ट और बिलिंग ईमेल पाएं।',
  'settings.smsAlerts': 'SMS अलर्ट',
  'settings.smsAlertsDesc': 'जरूरी अपॉइंटमेंट और इमरजेंसी अपडेट फोन पर पाएं।',
  'settings.systemNotifications': 'सिस्टम नोटिफिकेशन',
  'settings.systemNotificationsDesc': 'डैशबोर्ड में इन-ऐप नोटिफिकेशन दिखाएं।',
  'settings.appointmentReminders': 'अपॉइंटमेंट रिमाइंडर',
  'settings.appointmentRemindersDesc': 'आने वाले कंसल्टेशन से पहले रिमाइंडर भेजें।',
  'settings.weeklyReports': 'साप्ताहिक रिपोर्ट',
  'settings.weeklyReportsDesc': 'गतिविधि और जरूरी रिकॉर्ड का साप्ताहिक सारांश पाएं।',
  'settings.saveNotifications': 'नोटिफिकेशन सेव करें',
  'settings.dashboardAppearance': 'डैशबोर्ड दिखावट',
  'settings.theme': 'थीम',
  'settings.system': 'सिस्टम',
  'settings.light': 'लाइट',
  'settings.dark': 'डार्क',
  'settings.density': 'घनत्व',
  'settings.comfortable': 'आरामदायक',
  'settings.compact': 'कॉम्पैक्ट',
  'settings.spacious': 'स्पेशियस',
  'settings.language': 'भाषा',
  'settings.english': 'English',
  'settings.hindi': 'हिंदी',
  'settings.marathi': 'मराठी',
  'settings.timezone': 'टाइमजोन',
  'settings.indiaTime': 'भारतीय समय',
  'settings.easternTime': 'ईस्टर्न टाइम',
  'settings.london': 'लंदन',
  'settings.saveAppearance': 'दिखावट सेव करें',
  'settings.privacyData': 'प्राइवेसी और डेटा',
  'settings.usageAnalytics': 'यूसेज एनालिटिक्स',
  'settings.usageAnalyticsDesc': 'डैशबोर्ड विश्वसनीयता सुधारने के लिए गैर-मेडिकल उपयोग डेटा शेयर करें।',
  'settings.profileVisibility': 'प्रोफाइल दृश्यता',
  'settings.private': 'प्राइवेट',
  'settings.careTeamOnly': 'केयर टीम केवल',
  'settings.hospitalStaff': 'हॉस्पिटल स्टाफ',
  'settings.downloadData': 'मेरा डेटा डाउनलोड करें',
  'settings.savePrivacy': 'प्राइवेसी सेव करें',
  'option.overview': 'ओवरव्यू',
  'option.reports': 'रिपोर्ट',
  'option.billing': 'बिलिंग',
  'option.emergency': 'इमरजेंसी',
  'option.appointments': 'अपॉइंटमेंट',
  'option.records': 'मेडिकल रिकॉर्ड',
  'option.patients': 'मरीज',
  'option.earnings': 'कमाई',
  'option.schedule': 'शेड्यूल',
};

const mr = {
  'nav.dashboard': 'डॅशबोर्ड',
  'nav.manageUsers': 'यूजर व्यवस्थापन',
  'nav.manageDoctors': 'डॉक्टर व्यवस्थापन',
  'nav.managePatients': 'रुग्ण व्यवस्थापन',
  'nav.appointments': 'अपॉइंटमेंट',
  'nav.medicalRecords': 'मेडिकल रेकॉर्ड',
  'nav.billing': 'बिलिंग',
  'nav.departments': 'विभाग',
  'nav.reviews': 'रिव्ह्यू',
  'nav.analytics': 'अॅनालिटिक्स',
  'nav.emergency': 'इमर्जन्सी',
  'nav.importExport': 'इंपोर्ट/एक्सपोर्ट',
  'nav.reports': 'रिपोर्ट',
  'nav.notifications': 'नोटिफिकेशन',
  'nav.settings': 'सेटिंग्स',
  'nav.findDoctors': 'डॉक्टर शोधा',
  'nav.myAppointments': 'माझे अपॉइंटमेंट',
  'nav.labServices': 'लॅब सेवा',
  'nav.uploadFiles': 'फाइल अपलोड',
  'nav.myReports': 'माझे रिपोर्ट',
  'nav.myBilling': 'माझे बिलिंग',
  'nav.payments': 'पेमेंट',
  'nav.myReviews': 'माझे रिव्ह्यू',
  'nav.myPatients': 'माझे रुग्ण',
  'nav.consultations': 'कन्सल्टेशन',
  'nav.mySchedule': 'माझे शेड्यूल',
  'nav.myEarnings': 'माझी कमाई',
  'common.logout': 'लॉगआउट',
  'common.saving': 'सेव्ह होत आहे...',
  'common.updating': 'अपडेट होत आहे...',
  'role.admin': 'अॅडमिन',
  'role.doctor': 'डॉक्टर',
  'role.patient': 'रुग्ण',
  'settings.title': 'सेटिंग्स',
  'settings.subtitle': 'अकाउंट, सुरक्षा, नोटिफिकेशन आणि डॅशबोर्ड पसंती व्यवस्थापित करा',
  'settings.profile': 'प्रोफाइल',
  'settings.roleDetails': 'भूमिका तपशील',
  'settings.security': 'सुरक्षा',
  'settings.notifications': 'नोटिफिकेशन',
  'settings.appearance': 'दिसणे',
  'settings.privacy': 'प्रायव्हसी',
  'settings.saved': 'सेटिंग्स सेव्ह झाल्या.',
  'settings.saveError': 'सेटिंग्स सेव्ह करू शकलो नाही.',
  'settings.passwordSaved': 'पासवर्ड अपडेट झाला.',
  'settings.passwordError': 'पासवर्ड अपडेट करू शकलो नाही.',
  'settings.passwordLength': 'नवा पासवर्ड किमान 6 अक्षरांचा असावा.',
  'settings.passwordMismatch': 'नवा पासवर्ड आणि पुष्टी जुळत नाही.',
  'settings.profilePhoto': 'प्रोफाइल फोटो',
  'settings.personalInfo': 'वैयक्तिक माहिती',
  'settings.fullName': 'पूर्ण नाव',
  'settings.yourName': 'तुमचे नाव',
  'settings.emailAddress': 'ईमेल पत्ता',
  'settings.emailLocked': 'रजिस्ट्रेशननंतर ईमेल बदलता येत नाही.',
  'settings.phoneNumber': 'फोन नंबर',
  'settings.gender': 'लिंग',
  'settings.preferNot': 'सांगायचे नाही',
  'settings.male': 'पुरुष',
  'settings.female': 'महिला',
  'settings.other': 'इतर',
  'settings.dateOfBirth': 'जन्म तारीख',
  'settings.avatarUrl': 'अवतार URL',
  'settings.address': 'पत्ता',
  'settings.addressPlaceholder': 'रहिवासी पत्ता',
  'settings.saveProfile': 'प्रोफाइल सेव्ह करा',
  'settings.rolePreferences': 'भूमिका सेटिंग्स',
  'settings.specialization': 'स्पेशलायझेशन',
  'settings.experience': 'अनुभव',
  'settings.qualification': 'पात्रता',
  'settings.licenseNumber': 'लायसन्स नंबर',
  'settings.consultationFee': 'कन्सल्टेशन फी (Rs)',
  'settings.scheduleAlerts': 'शेड्यूल अलर्ट',
  'settings.scheduleAlertsDesc': 'अपॉइंटमेंट बदलल्यावर किंवा तातडीचा केस मिळाल्यावर कळवा.',
  'settings.adminDigest': 'अॅडमिन दैनिक सारांश',
  'settings.adminDigestDesc': 'रजिस्ट्रेशन, बिलिंग आणि इमर्जन्सीचा सारांश मिळवा.',
  'settings.criticalAlerts': 'महत्त्वाचे अलर्ट',
  'settings.criticalAlertsDesc': 'इमर्जन्सी आणि अकाउंट ब्लॉक घटना लगेच दाखवा.',
  'settings.defaultAdminDashboard': 'डिफॉल्ट अॅडमिन डॅशबोर्ड',
  'settings.defaultDoctorDashboard': 'डिफॉल्ट डॉक्टर डॅशबोर्ड',
  'settings.defaultPatientDashboard': 'डिफॉल्ट रुग्ण डॅशबोर्ड',
  'settings.careTeamSharing': 'केअर टीम रेकॉर्ड शेअरिंग',
  'settings.careTeamSharingDesc': 'असाइन डॉक्टरांना इमर्जन्सी, लॅब आणि भेट रेकॉर्ड पाहू द्या.',
  'settings.labResultEmails': 'लॅब रिजल्ट ईमेल',
  'settings.labResultEmailsDesc': 'लॅब रिपोर्ट उपलब्धता आणि अटॅचमेंट ईमेलवर पाठवा.',
  'settings.saveRole': 'भूमिका सेटिंग्स सेव्ह करा',
  'settings.currentPassword': 'सध्याचा पासवर्ड',
  'settings.newPassword': 'नवा पासवर्ड',
  'settings.confirmPassword': 'नवा पासवर्ड पुष्टी करा',
  'settings.twoFactor': 'टू-फॅक्टर व्हेरिफिकेशन',
  'settings.twoFactorDesc': 'संवेदनशील बदलांसाठी OTP व्हेरिफिकेशन मागा.',
  'settings.updatePassword': 'पासवर्ड अपडेट करा',
  'settings.saveSecurity': 'सुरक्षा सेटिंग्स सेव्ह करा',
  'settings.notificationPrefs': 'नोटिफिकेशन पसंती',
  'settings.emailNotifications': 'ईमेल नोटिफिकेशन',
  'settings.emailNotificationsDesc': 'अकाउंट, अपॉइंटमेंट, रिपोर्ट आणि बिलिंग ईमेल मिळवा.',
  'settings.smsAlerts': 'SMS अलर्ट',
  'settings.smsAlertsDesc': 'तातडीचे अपॉइंटमेंट आणि इमर्जन्सी अपडेट फोनवर मिळवा.',
  'settings.systemNotifications': 'सिस्टम नोटिफिकेशन',
  'settings.systemNotificationsDesc': 'डॅशबोर्डमध्ये इन-अॅप नोटिफिकेशन दाखवा.',
  'settings.appointmentReminders': 'अपॉइंटमेंट रिमाइंडर',
  'settings.appointmentRemindersDesc': 'येणाऱ्या कन्सल्टेशनपूर्वी रिमाइंडर पाठवा.',
  'settings.weeklyReports': 'साप्ताहिक रिपोर्ट',
  'settings.weeklyReportsDesc': 'क्रियाकलाप आणि महत्त्वाच्या रेकॉर्डचा साप्ताहिक सारांश मिळवा.',
  'settings.saveNotifications': 'नोटिफिकेशन सेव्ह करा',
  'settings.dashboardAppearance': 'डॅशबोर्ड दिसणे',
  'settings.theme': 'थीम',
  'settings.system': 'सिस्टम',
  'settings.light': 'लाइट',
  'settings.dark': 'डार्क',
  'settings.density': 'घनता',
  'settings.comfortable': 'आरामदायक',
  'settings.compact': 'कॉम्पॅक्ट',
  'settings.spacious': 'स्पेशियस',
  'settings.language': 'भाषा',
  'settings.english': 'English',
  'settings.hindi': 'हिंदी',
  'settings.marathi': 'मराठी',
  'settings.timezone': 'टाइमझोन',
  'settings.indiaTime': 'भारतीय वेळ',
  'settings.easternTime': 'ईस्टर्न टाइम',
  'settings.london': 'लंडन',
  'settings.saveAppearance': 'दिसणे सेव्ह करा',
  'settings.privacyData': 'प्रायव्हसी आणि डेटा',
  'settings.usageAnalytics': 'यूसेज अॅनालिटिक्स',
  'settings.usageAnalyticsDesc': 'डॅशबोर्ड सुधारण्यासाठी नॉन-मेडिकल वापर डेटा शेअर करा.',
  'settings.profileVisibility': 'प्रोफाइल दृश्यता',
  'settings.private': 'प्रायव्हेट',
  'settings.careTeamOnly': 'केअर टीम फक्त',
  'settings.hospitalStaff': 'हॉस्पिटल स्टाफ',
  'settings.downloadData': 'माझा डेटा डाउनलोड करा',
  'settings.savePrivacy': 'प्रायव्हसी सेव्ह करा',
  'option.overview': 'ओव्हरव्ह्यू',
  'option.reports': 'रिपोर्ट',
  'option.billing': 'बिलिंग',
  'option.emergency': 'इमर्जन्सी',
  'option.appointments': 'अपॉइंटमेंट',
  'option.records': 'मेडिकल रेकॉर्ड',
  'option.patients': 'रुग्ण',
  'option.earnings': 'कमाई',
  'option.schedule': 'शेड्यूल',
};

const dictionaries = { en, hi, mr };

export function t(key, language = 'en') {
  return dictionaries[language]?.[key] || key;
}
