import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { FileText, Search, Calendar, User, Stethoscope, Download, Printer } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useAuth } from '@/context/AuthContext';
import { api } from '@/lib/api';

const typeIcons = { Diagnosis: '🩺', Prescription: '💊', 'Lab Report': '🧪', Imaging: '📷' };
const typeColors = { Diagnosis: 'bg-primary/10 text-primary', Prescription: 'bg-success/10 text-success', 'Lab Report': 'bg-warning/10 text-warning', Imaging: 'bg-info/10 text-info' };

export default function PatientRecords() {
  const { user } = useAuth();
  const [records, setRecords] = useState([]);
  const [search, setSearch] = useState('');
  const [typeFilter, setTypeFilter] = useState('All');
  const [loading, setLoading] = useState(true);
  const [viewRecord, setViewRecord] = useState(null);

  const loadRecords = async () => {
    setLoading(true);
    try {
      const data = await api.getRecords({ search, type: typeFilter });
      const recordsArray = data?.records || data || [];
      setRecords(recordsArray);
    } catch (e) { console.error(e); }
    setLoading(false);
  };

  useEffect(() => { loadRecords(); }, [user?.name, search, typeFilter]);

  const handleDownload = (rec) => {
    const content = `
MEDICAL RECORD
==============

Patient: ${rec.patient}
Doctor: ${rec.doctor}
Date: ${rec.date}
Type: ${rec.type}

Diagnosis:
${rec.diagnosis}

Prescription:
${rec.prescription || 'N/A'}

Notes:
${rec.notes || 'N/A'}

---
Generated by MediCore HMS
    `.trim();
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `record_${rec.patient}_${rec.date}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = (rec) => {
    const content = `
      <html><head><title>Medical Record</title><style>body{font-family:Arial;padding:40px;}h1{color:#10b981;}.field{margin:10px 0;}.label{font-weight:bold;color:#666;}</style></head><body>
      <h1>MediCore HMS - Medical Record</h1>
      <div class="field"><span class="label">Patient:</span> ${rec.patient}</div>
      <div class="field"><span class="label">Doctor:</span> ${rec.doctor}</div>
      <div class="field"><span class="label">Date:</span> ${rec.date}</div>
      <div class="field"><span class="label">Type:</span> ${rec.type}</div>
      <div class="field"><span class="label">Diagnosis:</span> ${rec.diagnosis}</div>
      <div class="field"><span class="label">Prescription:</span> ${rec.prescription || 'N/A'}</div>
      <div class="field"><span class="label">Notes:</span> ${rec.notes || 'N/A'}</div>
      </body></html>
    `;
    const w = window.open('', '_blank');
    w.document.write(content);
    w.document.close();
    w.print();
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="font-heading text-2xl font-bold text-foreground">My Medical Records</h1>
        <p className="text-muted-foreground">View, download, and print your medical records</p>
      </div>

      {/* Search & Filter */}
      <div className="flex flex-col sm:flex-row gap-4">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
          <Input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search records..." className="pl-10" />
        </div>
        <div className="flex gap-2 flex-wrap">
          {['All', 'Diagnosis', 'Prescription', 'Lab Report', 'Imaging'].map(t => (
            <button key={t} onClick={() => setTypeFilter(t)}
              className={`px-3 py-1.5 rounded-lg text-sm font-medium transition-colors ${typeFilter === t ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground hover:bg-muted/80'}`}>
              {t}
            </button>
          ))}
        </div>
      </div>

      {/* Records */}
      {loading ? (
        <div className="flex justify-center py-12"><div className="w-8 h-8 border-4 border-primary border-t-transparent rounded-full animate-spin" /></div>
      ) : records.length === 0 ? (
        <div className="text-center py-12 text-muted-foreground">No medical records found</div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {records.map((rec, i) => (
            <motion.div key={rec._id} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.05 }}
              className="bg-card rounded-2xl border border-border/60 p-5 hover:shadow-lg transition-all">
              <div className="flex items-start justify-between mb-3">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-xl bg-muted flex items-center justify-center text-lg">
                    {typeIcons[rec.type] || '📄'}
                  </div>
                  <span className={`px-2 py-0.5 rounded-full text-xs font-semibold ${typeColors[rec.type] || 'bg-muted text-muted-foreground'}`}>{rec.type}</span>
                </div>
                <div className="flex gap-1">
                  <Button variant="ghost" size="sm" className="h-8 w-8 p-0" onClick={() => handleDownload(rec)} title="Download">
                    <Download className="w-4 h-4" />
                  </Button>
                  <Button variant="ghost" size="sm" className="h-8 w-8 p-0" onClick={() => handlePrint(rec)} title="Print">
                    <Printer className="w-4 h-4" />
                  </Button>
                </div>
              </div>
              <h3 className="font-heading font-semibold text-foreground mb-2">{rec.diagnosis}</h3>
              {rec.prescription && (
                <div className="bg-success/5 rounded-lg p-3 mb-3">
                  <p className="text-xs font-medium text-success mb-1">Prescription</p>
                  <p className="text-sm text-foreground">{rec.prescription}</p>
                </div>
              )}
              <div className="flex items-center justify-between text-sm text-muted-foreground">
                <div className="flex items-center gap-2"><User className="w-3.5 h-3.5" /><span>{rec.doctor}</span></div>
                <div className="flex items-center gap-2"><Calendar className="w-3.5 h-3.5" /><span>{rec.date}</span></div>
              </div>
            </motion.div>
          ))}
        </div>
      )}
    </div>
  );
}
